CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS status (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS config (
    id SERIAL PRIMARY KEY,
    hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fetcher (
    id SERIAL PRIMARY KEY,
    config_id INTEGER NOT NULL REFERENCES config(id) ON DELETE CASCADE,
    url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS link (
    id SERIAL PRIMARY KEY,
    fetcher_id INTEGER NOT NULL REFERENCES fetcher(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    title TEXT,
    content TEXT,
    embedding VECTOR(768),
    status_id INTEGER NOT NULL REFERENCES status(id)
);
